# Generated by Django 4.2.6 on 2023-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_text_remove_daily_menu_about1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=254, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.RenameModel(
            old_name='Daily_Menu',
            new_name='DailyMenu',
        ),
        migrations.RenameModel(
            old_name='Todays_special',
            new_name='OurMenus',
        ),
        migrations.RenameModel(
            old_name='Popular_Items',
            new_name='PopularItems',
        ),
        migrations.RenameModel(
            old_name='Our_menus',
            new_name='TodaysSpecial',
        ),
        migrations.AlterModelOptions(
            name='ourmenus',
            options={'verbose_name': 'Our_menus', 'verbose_name_plural': 'Our_menus'},
        ),
        migrations.AlterModelOptions(
            name='todaysspecial',
            options={'verbose_name': 'Todays_special', 'verbose_name_plural': 'Todays_special'},
        ),
    ]
