# Generated by Django 4.2.6 on 2024-08-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contact_rename_daily_menu_dailymenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
